apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kpurzs8hn-nodejs
  janus-idp.io/tekton: kpurzs8hn-nodejs
  backstage.io/kubernetes-id: kpurzs8hn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kpurzs8hn-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
